### ISSUE TITLE
note lại 1 số phần của trang admin

### ISSUE THREAD

**Issue by thelocal69** [vunh195/adminpage-voucher#1]
1. merchant còn thiếu status active or deactive
2. warehouse vẫn add khi thiếu field, chứa nhiều giá trị mặc định nên vẫn cho add (cần bắt lỗi)

**Comment by thelocal69** [comment]
Về 2 field available From và To thì admin sẽ nhập ngày tháng năm yyyy/dd/mm và thời gian hh:MM:ss kiểu dữ liệu timestamp

**Comment by vunh195** [comment]
DONE
